spring:
   cloud:
      gateway:
         httpclient:
            ssl:
               use-insecure-trust-manager: true
         discovery:
            locator:
               enabled: ${DISCOVERY_LOCATOR:true}
               lower-case-service-id: true
      loadbalancer:
        retry:
          enabled: true
oauth2:
   loginUrl: ${OAUTH_URL:http://:172.20.72.134:8085}/login
   authorizeUrl: ${OAUTH_URL:http://:172.20.72.134:8085}/oauth/authorize
   tokenUrl: ${OAUTH_URL:http://:172.20.72.134:8085}/oauth/token
   clientId: ${OAUTH_CLIENTID:baidu}
   secert: ${OAUTH_SECERT:12345}
   authorizationGrantType: authorization_code
   redirectUri: http://mucala.org
   userInfouri: ${OAUTH_URL:http://:172.20.72.134:8085}/user/me
   logoutOAuth2Uri: ${OAUTH_URL:http://:172.20.72.134:8085}/logout