spring:
  cloud:
    inetutils:
      ignored-interfaces: eth0
      preferred-networks: 10.0
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
      discovery:
        locator:
          enabled: ${DISCOVERY_LOCATOR:false}
  redis:
    host: ${REDIS_HOST:172.18.222.59}
    port: ${REDIS_PORT:6379}
    database: 0
    password: ${REDIS_PASSWORD:moria2019}
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1m
logging:
  level:
    org.springframework.cloud.gateway: INFO

oauth2:
  loginUrl: ${OAUTH_URL:http://:macula-cloud-oauth:8080}/login
  authorizeUrl: ${OAUTH_URL:http://:macula-cloud-oauth:8080}/oauth/authorize
  tokenUrl: ${OAUTH_URL:http://:macula-cloud-oauth:8080}/oauth/token
  client_id: ${OAUTH_CLIENTID:baidu}
  secert: ${OAUTH_SECERT:12345}
  authorizationGrantType: authorization_code
  redirect_uri: http://mucala.org
  userInfouri: ${OAUTH_URL:http://:macula-cloud-oauth:8080}/user/me
  logoutOAuth2Uri: ${OAUTH_URL:http://:macula-cloud-oauth:8080}/logout
adfs:
  userInfouri: http://${ADFS_URL:macula-cloud-adfsclient:8082}/adfs/userInfo
  logoutADFSUri: https://adfs-test.infinitus-int.com:8000/logout.aspx
