oauth2:
  loginUrl: ${OAUTH_URL:http://:oauth:8080}/login
  authorizeUrl: ${OAUTH_URL:http://:oauth:8080}/oauth/authorize
  tokenUrl: ${OAUTH_URL:http://:oauth:8080}/oauth/token
  client_id: ${OAUTH_CLIENTID:baidu}
  secert: ${OAUTH_SECERT:12345}
  authorizationGrantType: authorization_code
  redirect_uri: http://mucala.org
  userInfouri: ${OAUTH_URL:http://:oauth:8080}/user/me
  logoutOAuth2Uri: ${OAUTH_URL:http://:oauth:8080}/logout
adfs:
  userInfouri: http://${ADFS_URL:adfsclient:8082}/adfs/userInfo
  logoutADFSUri: https://adfs-test.infinitus-int.com:8000/logout.aspx