eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USER:admin}:${EUREKA_PASSWORD:admin}@${EUREKA_HOST:39.108.79.100}:${EUREKA_PORT:8761}/eureka/
spring:
  cloud:
    inetutils:
      ignored-interfaces: eth0
      preferred-networks: 10.0
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
      discovery:
        locator:
          enabled: ${DISCOVERY_LOCATOR:false}
  redis:
    host: ${REDIS_HOST:120.79.227.119}
    port: ${REDIS_PORT:6379}
    database: 13
    password: ${REDIS_PASSWORD:moria2019}
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1m
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
oauth2:
  loginUrl: ${OAUTH_URL:http://:10.108.1.61:8087}/login
  authorizeUrl: ${OAUTH_URL:http://:10.108.1.61:8087}/oauth/authorize
  tokenUrl: ${OAUTH_URL:http://:10.108.1.61:8087}/oauth/token
  client_id: ${OAUTH_CLIENTID:baidu}
  secert: ${OAUTH_SECERT:12345}
  authorizationGrantType: authorization_code
  redirect_uri: http://mucala.org
  userInfouri: ${OAUTH_URL:http://:10.108.1.61:8087}/user/me
  logoutOAuth2Uri: ${OAUTH_URL:http://:10.108.1.61:8087}/logout
adfs:
  userInfouri: http://${ADFS_URL:adfsclient:8082}/adfs/userInfo
  logoutADFSUri: https://adfs-test.infinitus-int.com:8000/logout.aspx